name: Manual Dummy Deploy to AWS Lambda

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create dummy file
      run: |
        echo "import random" > dummy_lambda.py
        echo "print(random.random())" >> dummy_lambda.py
        echo "print('Hello from dummy Lambda!')" >> dummy_lambda.py
        zip -r lambda.zip dummy_lambda.py
        zip -r rate.zip backend/rate

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.LAMBDA_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.LAMBDA_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Upload dummy file to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name http-function-url-tutorial \
          --zip-file fileb://lambda.zip

