name: Manual Dummy Deploy to AWS Lambda

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Create dummy file
      run: |
        echo "print('Hello from dummy Lambda!')" > dummy_lambda.py
        zip -r lambda.zip dummy_lambda.py
        zip -r rate.zip backend/rate

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload dummy file to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name http-function-url-tutorial \
          --zip-file fileb://lambda.zip
        aws lambda update-function-code \
          --function-name rate \
          --zip-file fileb://rate.zip

